tab-width: 4
use-tabs: false
trailing-commas: es6
semicolons: true
arrow-parens: always
bracket-spacing: true
finder:
  exclude:
    - "modules"
    - "node_modules"
    - "storage"
    - "vendor"
  name:
    - "*.js"
    - "*.jsx"
  not-name:
    - "*.min.js"
  path:
    - "/api"