version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: projects-lab-docker
      MYSQL_USER: admin-docker
      MYSQL_PASSWORD: password-docker
      MYSQL_ROOT_PASSWORD: root-password-docker

  api:
    build:
      context: api
      dockerfile: .deploy/Dockerfile
    ports:
      - 8000:4444
    environment:
      NODE_ENV: docker

  adminer:
    image: adminer:latest
    restart: always
    ports:
    - 8888:8080

  client:
    build:
      context: client
      dockerfile: .deploy/Dockerfile
    volumes:
    - .:/app
    ports:
    - 7000:80
    env_file:
      - ./client/.env.docker
